export const COMMON_SET_CATEGORIES = "COMMON_SET_CATEGORIES";
export const COMMON_SET_ACTIVE_CATEGORY = "COMMON_SET_ACTIVE_CATEGORY";
export const COMMON_SET_CURRENCIES = "COMMON_SET_CURRENCIES";
export const COMMON_SET_ACTIVE_CURRENCY = "COMMON_SET_ACTIVE_CURRENCY";
export const COMMON_INIT_DATA = "COMMON_INIT_DATA";

export const CATEGORY_SET_PRODUCTS = "CATEGORY_SET_PRODUCTS";

export const CART_ADD_TO_CART = "CART_ADD_TO_CART";
export const CART_INCREMENT = "CART_INCREMENT";
export const CART_DECREMENT = "CART_DECREMENT";
export const CART_UPDATE_PROD_ATTRS = "CART_UPDATE_PROD_ATTRS";

export const PRODUCT_SET_PRODUCT = "PRODUCT_SET_PRODUCT";
export const PRODUCT_SET_GALLERY_INDEX = "PRODUCT_SET_GALLERY_INDEX";
